"""Install the Midnight S1 v1.7 compact scoring core and regenerate stat-priority tables."""

from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path

import build_bis_catalog as catalog


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = REPO_ROOT / "DOC" / "MidnightS1_MPlus_Addon_DB_v1.7.lua"
RUNTIME_TARGET = REPO_ROOT / "ABProfileManager" / "Data" / "MidnightS1MPlusDB.lua"
CATALOG_TARGET = REPO_ROOT / "ABProfileManager" / "Data" / "BISCatalog.lua"
STAT_TARGET = REPO_ROOT / "ABProfileManager" / "Data" / "StatPriorities.lua"
TABLE_TARGET = REPO_ROOT / "ABProfileManager" / "Data" / "StatPriorityTable.lua"

SPEC_ALIASES = {
    "DRUID_RESTO": "DRUID_RESTORATION",
    "HUNTER_BEASTMASTERY": "HUNTER_BEAST_MASTERY",
    "PRIEST_DISC": "PRIEST_DISCIPLINE",
}


def quoted_field(raw: str, field: str) -> str:
    match = re.search(rf'\b{re.escape(field)}="([^"]*)"', raw)
    if not match:
        raise ValueError(f"Missing {field} in compact spec row: {raw[:120]}")
    return match.group(1)


def parse_compact_spec_policies(text: str) -> dict[int, dict[str, object]]:
    match = re.search(r"DB\.SPECS\s*=\s*\{\n(?P<body>.*?)\n\}\n\nlocal function", text, re.S)
    if not match:
        raise ValueError("DB.SPECS block not found")

    policies: dict[int, dict[str, object]] = {}
    for raw_key, raw in re.findall(r"^\s{2}([A-Z0-9_]+)\s*=\s*\{(.*)\},\s*$", match.group("body"), re.M):
        spec_key = SPEC_ALIASES.get(raw_key, raw_key)
        spec_id = catalog.SPEC_KEY_TO_ID.get(spec_key)
        if not spec_id:
            raise ValueError(f"Unknown compact spec key: {raw_key}")
        weights = {
            name: int(value)
            for name, value in re.findall(r'\["([^"]+)"\]\s*=\s*(\d+)', raw)
        }
        if len(weights) != 4:
            raise ValueError(f"Expected four weights for {raw_key}, got {weights!r}")
        policies[spec_id] = {
            "specKo": quoted_field(raw, "specKo"),
            "primary": quoted_field(raw, "primary"),
            "secondaryPriority": quoted_field(raw, "priority"),
            "secondaryOrder": list(weights),
            "secondaryWeights": weights,
        }
    if len(policies) != len(catalog.SPEC_NAMES):
        raise ValueError(f"Expected {len(catalog.SPEC_NAMES)} specs, got {len(policies)}")
    return policies


def rewrite_header(text: str) -> str:
    return text.replace(
        "Generated by scripts/build_bis_catalog.py from DOC/MidnightS1_MPlus_Addon_DB_v1.3.lua.",
        "Generated by scripts/build_bis_runtime_scoring.py from DOC/MidnightS1_MPlus_Addon_DB_v1.7.lua.",
    ).replace(
        "Midnight Season 1 representative single stat priorities (v1.3 policy).",
        "Midnight Season 1 representative single stat priorities (v1.7 compact scoring policy).",
    )


def replace_lua_string_field(line: str, field: str, value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return re.sub(
        rf'(\b{re.escape(field)}\s*=\s*")(?:(?:\\.)|[^"\\])*(")',
        rf"\g<1>{escaped}\g<2>",
        line,
        count=1,
    )


def rewrite_catalog_priorities(text: str, policies: dict[int, dict[str, object]]) -> str:
    lines = text.splitlines(keepends=True)
    current_spec_id: int | None = None
    in_policy_table = False
    for index, line in enumerate(lines):
        if line.startswith("ns.Data.BISSpecPolicies = {"):
            in_policy_table = True
            current_spec_id = None
            continue
        spec_match = re.match(r"^\s*\[(\d+)\]\s*=\s*\{", line)
        if spec_match:
            current_spec_id = int(spec_match.group(1))
        policy = policies.get(current_spec_id or 0)
        if not policy:
            continue
        priority = str(policy["secondaryPriority"])
        if in_policy_table and "secondaryPriority" in line:
            lines[index] = replace_lua_string_field(line, "secondaryPriority", priority)
        elif not in_policy_table and "{ slot =" in line and "statPrioritySummary" in line:
            lines[index] = replace_lua_string_field(line, "statPrioritySummary", priority)
    return "".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    args = parser.parse_args()

    source = args.source.resolve()
    text = source.read_text(encoding="utf-8")
    policies = parse_compact_spec_policies(text)
    shutil.copyfile(source, RUNTIME_TARGET)
    CATALOG_TARGET.write_text(
        rewrite_catalog_priorities(CATALOG_TARGET.read_text(encoding="utf-8"), policies),
        encoding="utf-8",
    )
    STAT_TARGET.write_text(rewrite_header(catalog.render_stat_priorities(policies)), encoding="utf-8")
    TABLE_TARGET.write_text(rewrite_header(catalog.render_stat_priority_table(policies)), encoding="utf-8")
    print(f"ok: installed compact scoring core and regenerated {len(policies)} spec priorities")


if __name__ == "__main__":
    main()
